### ISSUE TITLE
The username and password were incorrect.

### ISSUE THREAD

**Issue by wjterveld** [strongswan/strongMan#122]
unable to login to the strongman interface.. How do I configure the DB with a user account?

**Comment by wjterveld** [comment]
I all so keep getting "/var/run/charon.vici doesn't exist!"

**Comment by tobiasbrunner** [comment]
> unable to login to the strongman interface.. How do I configure the DB with a user account?

If you follow the [README](https://github.com/strongswan/strongMan/blob/master/README.md), a database with default user should have been created (the credentials are also listed further down).

> I all so keep getting "/var/run/charon.vici doesn't exist!"

This happens if strongMan can't connect to the strongSwan IKE daemon, or more specifically, the socket created by the _vici_ plugin. So that must be running with the plugin loaded.
