### ISSUE TITLE
No Such File or Directory .../sqlite3

### ISSUE THREAD

**Issue by dennis-it-net** [strongswan/strongMan#133]
I'm getting the error when running setup.py:

[Errno 2] No such file or directory: '/home/dennis/strongMan/strongMan/db.sqlite3'

I didn't see sqlite3 in the list of requirements.

**Comment by tobiasbrunner** [comment]
You don't. But the default database engine is SQLite and the script apparently attempts to delete any existing database. Since Python 3.8 this apparently raises an exception if the file doesn't exist. However, unless you use the `migrate` command with `--delete-migrations`, that exception is caught, so that should only result in a log message, not a fatal error.

**Comment by dennis-it-net** [comment]
Thanks for the reply. So what's the exact command to get around this? 

Is it:
./setup.py migrate --delete-migrations
then ./setup.py install

**Comment by tobiasbrunner** [comment]
> So what's the exact command to get around this?

Around what? It's just a log message.
