### ISSUE TITLE
generic questions

### ISSUE THREAD

**Issue by aspx1981** [strongswan/strongMan#136]
Hello everybody,

just some questions:

1. how is it possible to change the web-gui admin username (John) ?
2. why my config in the web-gui is empty while ipsec.conf is full of configuration ?
3. where is stored the web-gui config ?

thanks,
bye

**Comment by tobiasbrunner** [comment]
> how is it possible to change the web-gui admin username (John) ?

During the initial setup the account data is loaded from [initial_data.json](https://github.com/strongswan/strongMan/blob/master/strongMan/fixtures/initial_data.json). Afterwards, you need to directly change the database.

> why my config in the web-gui is empty while ipsec.conf is full of configuration ?

Because there is no relation between the two whatsoever. strongMan stores its config in a database and configures the daemon directly via [vici](https://docs.strongswan.org/docs/5.9/plugins/vici.html) interface.

> where is stored the web-gui config ?

In a database that's stored in the program directory.

**Comment by karmendra** [comment]
How do I add a new site to site connection with authby=psk?

**Comment by LarsTi** [comment]
As far as i know, PSKs are not supported via strongMAN.

see #108 and #105

**Comment by karmendra** [comment]
@LarsTi thanks for pointing that, I should have searched bit more. but the thing is many of my peers (with cisco asa etc) use PSK and I am kind of forced. I think only option left is not to use strongman.
